export const SERVICE_INFO = [
  {
    slug: "spoedloodgieter",
    name: "Spoedloodgieter",
    desc: "Acute lekkage of een gesprongen leiding? Onze spoedloodgieters beperken de waterschade onmiddellijk en herstellen ter plaatse — dag en nacht.",
    bullets: [
      "Lekkages opsporen en herstellen",
      "Gesprongen leidingen vervangen",
      "Defect sanitair herstellen",
      "Waterschade direct beperken",
    ],
    price: "vanaf €65/uur",
  },
  {
    slug: "elektricien",
    name: "Elektricien",
    desc: "Stroompanne, kortsluiting of een defecte zekeringkast? Onze elektriciens werken veilig en volledig conform AREI.",
    bullets: [
      "Stroompannes en kortsluiting verhelpen",
      "Zekeringkasten vervangen en uitbreiden",
      "Stopcontacten, schakelaars en verlichting",
      "Werken conform AREI, met attest",
    ],
    price: "vanaf €65/uur",
  },
  {
    slug: "ontstopping",
    name: "Ontstopping",
    desc: "Verstopte wc, afvoer of riolering? Wij ontstoppen definitief met professionele apparatuur, hogedruk en camera-inspectie.",
    bullets: [
      "WC-, afvoer- en gootsteenontstopping",
      "Riolering reinigen met hogedruk",
      "Camera-inspectie bij terugkerende problemen",
      "Geurhinder opsporen en verhelpen",
    ],
    price: "vanaf €99",
  },
  {
    slug: "verwarming",
    name: "Verwarming",
    desc: "Ketelpanne of een verwarming die niet meer meewerkt? Wij herstellen, onderhouden en stellen uw installatie optimaal af.",
    bullets: [
      "Ketelherstelling alle merken",
      "Wettelijk ketelonderhoud",
      "Radiatoren plaatsen en ontluchten",
      "Thermostaten en zone-regeling",
    ],
    price: "vanaf €65/uur",
  },
  {
    slug: "sanitair-renovatie",
    name: "Sanitaire renovatie",
    desc: "Van verouderde badkamer naar een strak eindresultaat: wij verzorgen de complete sanitaire renovatie, van leidingwerk tot afwerking.",
    bullets: [
      "Complete badkamerrenovatie",
      "Toiletrenovatie en verplaatsing",
      "Leidingwerk volledig vernieuwen",
      "Inloopdouches en kranen plaatsen",
    ],
    price: "offerte op maat",
  },
  {
    slug: "airco",
    name: "Airco & klimaat",
    desc: "Koele zomers en efficiënt verwarmen in de winter: wij installeren en onderhouden airco's en warmtepompen op maat van uw woning.",
    bullets: [
      "Airco-installatie split en multi-split",
      "Warmtepompen lucht-lucht",
      "Onderhoud en herstelling",
      "Advies op maat van uw ruimtes",
    ],
    price: "offerte op maat",
  },
  {
    slug: "laadpalen",
    name: "Laadpalen",
    desc: "Uw elektrische wagen thuis of op het werk laden? Wij installeren slimme laadpalen, inclusief aanpassing van de zekeringkast.",
    bullets: [
      "Laadpalen voor thuis",
      "Laadinfrastructuur voor bedrijven",
      "Slimme laadpalen met app en load balancing",
      "Uitbreiding zekeringkast inbegrepen",
    ],
    price: "vanaf €850 incl. plaatsing",
  },
];
